# NumPy - Introdução

## Números complexos

In [1]:
import numpy as np
arr = np.array([1.j + 3, 4.j + 2])
arr

array([3.+1.j, 2.+4.j])

In [2]:
arr.real

array([3., 2.])

In [3]:
arr.imag

array([1., 4.])

In [4]:
arr.dtype

dtype('complex128')

## Iterando nos itens do array com flat

In [5]:
arr = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11]])
itens = arr.flat
for item in itens:
    print(item)

0
1
2
3
4
5
6
7
8
9
10
11


In [7]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr.flat[6]

7

In [8]:
arr.flat[[0,3]]

array([1, 4])

In [10]:
arr.flat = 8
arr

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [11]:
arr.flat[[0,1,7]] = 3
arr

array([[3, 3, 8, 8],
       [8, 8, 8, 3],
       [8, 8, 8, 8]])

## Convertendo array em lista

In [12]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
lista = arr.tolist()
lista

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [13]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])