# CURSO USANDO PYTHON PARA ANÁLISE DE DADOS

https://www.udemy.com/usando-python-para-analise-de-dados

Evaldo Wolkers

## NumPy

## Transposição de arrays e troca de eixos

![imagens\img0.png](imagens/img0.png)

![imagens/img1.png](imagens/img1.png)

In [2]:
import numpy as np

In [3]:
arr = np.arange(15).reshape((3,5))

In [4]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [7]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [12]:
arr = np.arange(24).reshape((2,3,4))

In [13]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
arr.shape # Visualizar as dimensões do array

(2, 3, 4)

Nosso array possui duas dimensões, três linhas e quatro colunas (2, 3, 4).

In [21]:
x = arr.transpose(2, 0, 1)
# Vai ficar (4, 2, 3), pois, o índice 0 possui o valor 2, o índice 1 possui o valor 3 e o índice 2 possui o valor 4.

In [19]:
x

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [18]:
x.shape

(4, 2, 3)

Podemos trocar os eixos usando o método swapaxes que recebe por parâmetro dois inteiros que são os números dos eixos que serão trocados.

In [22]:
arr = np.arange(24).reshape((2,3,4))

In [23]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [24]:
arr.shape

(2, 3, 4)

In [28]:
x = arr.swapaxes(2,1) # Trocando os eixos 3 e 4 (linhas e colunas).

In [29]:
x

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [27]:
x.shape

(2, 4, 3)