# NumPy - Introdução

## Outros métodos do ndarray

In [2]:
import numpy as np


lista = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
myArray = np.array(lista)
print(np.ndim(myArray))
lista = [[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]
myArray = np.array(lista)
print(np.ndim(myArray))

2
3


In [3]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr.dtype)
arr_float = arr.astype(np.float32)
print(arr_float.dtype)
print(arr_float)
print(arr)

int32
float32
[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [4]:
import numpy as np

np.diag([10, 50, 100, 150, 200])

array([[ 10,   0,   0,   0,   0],
       [  0,  50,   0,   0,   0],
       [  0,   0, 100,   0,   0],
       [  0,   0,   0, 150,   0],
       [  0,   0,   0,   0, 200]])

In [6]:
import numpy as np

arr = np.array([1,2,3,4,5])
arr.size

5

In [7]:
arr.itemsize

4

In [8]:
arr.nbytes

20

In [9]:
arr.size * arr.itemsize

20

In [11]:
import numpy as np

arr = np.array([[0,1,2,3],[4,5,6,7]])
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
arr.transpose()

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [13]:
import numpy as np

arr = np.array([[0,1,2],[3,4,5]])
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
arr.resize(3,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5]])