# NumPy - Introdução

## O que é o NumPy

O NumPy, abreviatura de Numerical Python (Python numérico), é um dos pacotes básicos mais importantes para processamento numérico em Python. A maioria dos pacotes de processamento com funcionalidades científicas utiliza objetos array do NumPy para troca de dados.<br>
Veja alguns recursos que você encontrará no NumPy:<br>
* Ndarray: Um array multidimensional eficaz que oferece operações matemáticas rápidas, orientadas a arrays, e recursos flexíveis de broadcasting.<br>
* Funções matemáticas para operações rápidas em arrays de dados inteiros, sem que seja necessário escrever laços.<br>
* Ferramentas para ler/escrever dados de array em disco e trabalhar com arquivos mapeados em memória.<br>
* Recursos para álgebra linear, geração de números aleatórios e transformadas de Fourier.<br>
* Uma API C para conectar o NumPy a bibliotecas escritas em C, C++ ou FORTRAN.<br>

## Array NumPy - ndarray

Um dos principais recursos do NumPy é seu objeto array N-dimensional, ou ndarray, que é um contêiner rápido e flexível para conjuntos de dados grandes em Python.<br>
Um ndarray é um contêiner genérico multidimensional para dados homogêneos. Isso significa que todos os elementos devem ser do mesmo tipo.

![Vetor](img/vetor.png)


Um vetor (array uni-dimensional) é uma variável que armazena vários valores do mesmo tipo. Para acessar um dos valores usamos o índice, começando por zero:<br>
a = x[1]<br>
Neste caso o valor de “a” é 20.


In [1]:
# Lista com Python
x = [10, 20, 30, 40]
a = x[1]
print(a)

20


In [2]:
# Array com NumPy
import numpy as np
x = np.array([10, 20, 30, 10])
a = x[1]
print(a)

20


![Matriz](img/matriz.png)

Uma Matriz (array multi-dimensional) é um vetor de vetores:<br>
a = x[1][2]<br>
Neste caso o valor de “a” é 60.


In [14]:
x = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90],[100, 110, 120]])
a = x[1,2]
print(a)

60


Uma maneira fácil de criar um array é usando a função array. Ela aceita qualquer objeto do tipo sequência (incluindo outros arrays) e gera um novo array NumPy contendo os dados recebidos.<br>



In [3]:
myList = [0, 1, 2, 3, 4, 5]
myArray = np.array(myList)
print(myArray)

[0 1 2 3 4 5]


Todo array tem um **shape**, ou seja, uma tupla que indica o tamanho de cada dimensão, e um **dtype**, que é um objeto que descreve o tipo de dado do array. A menos que seja explicitamente especificado, np.array tentará inferir um bom tipo de dado para o array que ele criar. Esse tipo de dado é armazenado em dtype (conjunto de metadados).<br>

In [4]:
print(myArray.shape) # (6,)
print(myArray.dtype) # int32

(6,)
int32


Podemos inicializar arrays NumPy de listas Python aninhadas e acessar elementos usando colchetes.
Exemplo de uma lista Python aninhada:
[[1, 2, 3], [4, 5, 6]]<br>

In [5]:
myList = [[0, 1, 2, 3, 4, 5], [10, 20, 30, 40, 50, 60]]
myArray = np.array(myList)
print(myArray)

[[ 0  1  2  3  4  5]
 [10 20 30 40 50 60]]


Veja mais alguns exemplos:

In [6]:
import numpy as np

myList = [[1, 2, 3], [4, 5, 6]]

# índice
#[     0    ,     1     ]
#[ [0][1][2], [0][1][2] ]

# Posicionamento
#[ [0,0][0,1][0,2],
#  [1,0][1,1][1,2] ]

# Valores
#[ [1][2][3],[4][5][6] ]

print(type(myList)) # <class 'list'>
myArray = np.array(myList)
print(type(myArray)) # <class 'numpy.ndarray'>
print(myArray.shape) # (2, 3)
print(myArray.dtype) # dtype('int32')
print(myArray[0][0], myArray[0][1], myArray[0][2]) # 1 2 3
print(myArray[1][0], myArray[1][1], myArray[1][2]) # 4 5 6
myArray[0][0] = 10 # Alterando o conteúdo da posição [0][0] que era "1" para "10"
print(myArray) # [[10  2  3] [ 4  5  6]]
a = myArray[0,0]
print(a) # 10
a = myArray[1,2]
print(a) # 6


<class 'list'>
<class 'numpy.ndarray'>
(2, 3)
int32
1 2 3
4 5 6
[[10  2  3]
 [ 4  5  6]]
10
6


## Tipos numéricos NumPy

Python tem um tipo inteiro, um tipo float e um tipo complexo. Contudo, isto não é o suficiente para computação científica e, por esse motivo, o NumPy tem muito mais tipos de dados com diferentes precisão, dependentes dos requisitos de memória.<br>
Na prática, precisamos de mais tipos com precisão variável e, portanto, de diferentes tamanhos.<br><br>
A maioria dos tipos numéricos NumPy termina com um número.<br>
Este número indica o número de bits associados ao tipo. A tabela a seguir fornece uma visão geral dos tipos numéricos do NumPy:

![Tipos Numéricos](img/tiposnumericos.png "Tipos numéricos NumPy")

## Comparando velocidade de listas Python com arrays NumPy

Os algoritmos baseados no NumPy são de 10 a 100 vezes mais rápidos (ou mais) do que suas contrapartidas em Python puro, além de utilizarem significativamente menos memória.<br>
Vamos fazer um teste usando a função mágica %time para conferirmos a velocidade da função soma do Python sobre uma lista e da função soma do NumPy sobre um array.

In [7]:
myList = list(range(9999999))
myArray = np.arange(9999999)

%time sum(myList)
%time np.sum(myArray)

Wall time: 336 ms
Wall time: 5.01 ms


-2024260031

## Funções para criação de arrays

O NumPy também fornece funções para criar arrays com valores preenchidos.<br>
* ones, ones_like: gera um array preenchido com uns (1s) com o formato e dtype especificados. ones_like aceita outro array e gera um array de uns com o mesmo formato e dtype.<br>
* zeros, zeros_like: similar a ones e ones_like, porém, gera arrays com zeros (0s).

In [8]:
a = np.ones((3, 2)) # Cria um array 3x2 preenchido com números 1.
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
a = np.zeros((3, 2)) # Cria um array 3x2 preenchido com zeros.
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


* full, full_like: gera um array com o formato e o dtype especificados, preenchendo com o valor informado, full_like aceita outro array e gera um array preenchido com o mesmo formato e dtype.<br>
* eye, identity: cria uma matriz-identidade quadrada N x N (1s na diagonal e 0s nas demais posições).

In [10]:
a = np.full((3, 2), 7) # Cria um array 3x2 preenchido com números 7.
print(a)

[[7 7]
 [7 7]
 [7 7]]


In [11]:
a = np.eye(4) # Cria um array 4x4 2d com números "1" na diagonal e o restante com zero.
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


* arange: é uma versão da função range de Python com valor de array.

In [12]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


## Outros métodos do ndarray

## Realizando cálculos com arrays

Os arrays permitem realizar operações matemáticas em blocos inteiros de dados usando uma sintaxe semelhante às operações equivalentes entre elementos escalares.

In [13]:
myList = [[1,2,3],[4,5,6],[7,8,9]]
myArray = np.array(myList)
print(f"myArray: {myArray}")

multiplica = myArray * 10
print(f"multiplica: {multiplica}")

soma = myArray + 1
print(f"soma: {soma}")

myArray: [[1 2 3]
 [4 5 6]
 [7 8 9]]
multiplica: [[10 20 30]
 [40 50 60]
 [70 80 90]]
soma: [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
