# CURSO USANDO PYTHON PARA ANÁLISE DE DADOS

https://www.udemy.com/usando-python-para-analise-de-dados

Evaldo Wolkers

## pandas

### Funcionalidades Essenciais - Aritmética e alinhamento de dados

In [3]:
import pandas as pd

In [19]:
serie1 = pd.Series([18.7, 4.8, 6.6, -2.5], index=['um', 'dois', 'tres', 'quatro'])

In [21]:
serie1

um        18.7
dois       4.8
tres       6.6
quatro    -2.5
dtype: float64

In [4]:
serie2 = pd.Series([77.1, 3.5, -4.87, 5.1], index=['um', 'cinco', 'seis', 'quatro'])

In [22]:
serie2

um        77.10
cinco      3.50
seis      -4.87
quatro     5.10
dtype: float64

In [5]:
serie1 + serie2

cinco      NaN
dois       NaN
quatro     2.6
seis       NaN
tres       NaN
um        95.8
dtype: float64

In [45]:
import numpy as np

In [46]:
dataframe1 = pd.DataFrame(np.arange(16.).reshape((4,4)), columns=list('abcd'), index=["ES", "RJ", "SP", "MG"])

In [47]:
dataframe1

a     b     c     d
ES   0.0   1.0   2.0   3.0
RJ   4.0   5.0   6.0   7.0
SP   8.0   9.0  10.0  11.0
MG  12.0  13.0  14.0  15.0

In [48]:
dataframe2 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list('abc'), index=["ES", "RJ", "SP"])

In [49]:
dataframe2

a    b    c
ES  0.0  1.0  2.0
RJ  3.0  4.0  5.0
SP  6.0  7.0  8.0

In [50]:
dataframe1 + dataframe2

a     b     c   d
ES   0.0   2.0   4.0 NaN
MG   NaN   NaN   NaN NaN
RJ   7.0   9.0  11.0 NaN
SP  14.0  16.0  18.0 NaN

In [7]:
dataframe1 = pd.DataFrame({'ES': [1, 2]})

In [8]:
dataframe1

ES
0   1
1   2

In [9]:
dataframe2 = pd.DataFrame({'RJ': [3, 4]})

In [10]:
dataframe2

RJ
0   3
1   4

In [11]:
dataframe1 - dataframe2

ES  RJ
0 NaN NaN
1 NaN NaN

#### Métodos aritméticos com valores para preenchimento

In [51]:
dataframe1 = pd.DataFrame(np.arange(16.).reshape((4,4)), columns=list('abcd'), index=["ES", "RJ", "SP", "MG"])

In [52]:
dataframe2 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list('abc'), index=["ES", "RJ", "SP"])

In [53]:
dataframe3 = dataframe1.add(dataframe2)

In [54]:
dataframe3

a     b     c   d
ES   0.0   2.0   4.0 NaN
MG   NaN   NaN   NaN NaN
RJ   7.0   9.0  11.0 NaN
SP  14.0  16.0  18.0 NaN

In [55]:
dataframe3 = dataframe1.add(dataframe2, fill_value=0)

In [56]:
dataframe3

a     b     c     d
ES   0.0   2.0   4.0   3.0
MG  12.0  13.0  14.0  15.0
RJ   7.0   9.0  11.0   7.0
SP  14.0  16.0  18.0  11.0

![img/Imagem1](img/Imagem1.png)

In [57]:
df1 = pd.DataFrame([1, 2, 3])

In [58]:
df2 = pd.DataFrame([4, 5, 6])

In [61]:
df3 = df1.div(df2)

In [62]:
df3

0
0  0.25
1  0.40
2  0.50

In [63]:
df4 = df1.rdiv(df2)

In [64]:
df4

0
0  4.0
1  2.5
2  2.0

#### Operações entre DataFrame e Series

In [66]:
arr = np.arange(12.).reshape((3,4))

In [67]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [68]:
arr[0]

array([0., 1., 2., 3.])

In [69]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [110]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'), index=["ES", "RJ", "SP", "MG"])

In [111]:
frame

b     d     e
ES  0.0   1.0   2.0
RJ  3.0   4.0   5.0
SP  6.0   7.0   8.0
MG  9.0  10.0  11.0

In [112]:
series = pd.Series([0., 1., 2.], name="ES", index=["b", "d", "e"])
series

b    0.0
d    1.0
e    2.0
Name: ES, dtype: float64

In [98]:
subtracao = frame - series
subtracao

b    d    e
ES  0.0  0.0  0.0
RJ  3.0  3.0  3.0
SP  6.0  6.0  6.0
MG  9.0  9.0  9.0

In [113]:
frame

b     d     e
ES  0.0   1.0   2.0
RJ  3.0   4.0   5.0
SP  6.0   7.0   8.0
MG  9.0  10.0  11.0

In [114]:
series2 = pd.Series(range(3), index=["b", "e", "f"])
series2

b    0
e    1
f    2
dtype: int64

In [116]:
soma = frame + series2
soma

b   d     e   f
ES  0.0 NaN   3.0 NaN
RJ  3.0 NaN   6.0 NaN
SP  6.0 NaN   9.0 NaN
MG  9.0 NaN  12.0 NaN

In [117]:
frame

b     d     e
ES  0.0   1.0   2.0
RJ  3.0   4.0   5.0
SP  6.0   7.0   8.0
MG  9.0  10.0  11.0

In [118]:
series3 = frame['d']
series3

ES     1.0
RJ     4.0
SP     7.0
MG    10.0
Name: d, dtype: float64

In [120]:
sub = frame.sub(series3, axis='index')
sub

b    d    e
ES -1.0  0.0  1.0
RJ -1.0  0.0  1.0
SP -1.0  0.0  1.0
MG -1.0  0.0  1.0