# CURSO USANDO PYTHON PARA ANÁLISE DE DADOS

https://www.udemy.com/usando-python-para-analise-de-dados

WingSec Treinamento e Consultoria em Desenvolvimento de Sistemas

## NumPy

## Salvando e carregando arquivos

In [ ]:
import numpy as np

In [2]:
array = np.arange(10)

In [16]:
np.save('exemplo', array)

![image1.png](image1.png)

In [4]:
array_novo = np.load('exemplo.npy')

In [5]:
array_novo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
array_a = np.array([0,1,2,3,4,5,6,7,8,9])

In [7]:
array_b = np.array([10,11,12,13,14,15,16,17,18,19,20])

In [8]:
np.savez('exemplo2', a=array_a, b=array_b)

In [9]:
arrays = np.load('exemplo2.npz')

In [10]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arrays['b']

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
array_a = np.arange(9999)

In [13]:
array_b = np.arange(9999)

In [14]:
np.savez('exemplo3', a=array_a, b=array_b)

In [15]:
np.savez_compressed('exemplo4', a=array_a, b=array_b)

![image2.png](image2.png)