# CURSO USANDO PYTHON PARA ANÁLISE DE DADOS

https://www.udemy.com/usando-python-para-analise-de-dados

Evaldo Wolkers

## NumPy

## Indexação sofisticada (fancy indexing)

Indexação sofisticada (fancy indexing) é o termo adotado pelo NumPy para descrever a indexação usando arrays de inteiros.

Primeiro vamos importar a biblioteca Numpy.

In [16]:
import numpy as np

Em seguida criaremos um array 5 x 3 preenchido com zeros.!

In [17]:
arr = np.zeros((5,3))

In [18]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Depois vamos alimentar cada linha do array com valores de 0 a 4.

In [19]:
for i in range(5):
    arr[i] = i

In [20]:
arr

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

Veja a utilização de uma lista e de um ndarray para indexar um array.

In [21]:
lista = [4,3,1,0,2]

In [22]:
arr[lista]

array([[4., 4., 4.],
       [3., 3., 3.],
       [1., 1., 1.],
       [0., 0., 0.],
       [2., 2., 2.]])

In [23]:
arr2 = np.array([4,1,3,2,0])

In [24]:
arr[arr2]

array([[4., 4., 4.],
       [1., 1., 1.],
       [3., 3., 3.],
       [2., 2., 2.],
       [0., 0., 0.]])

Para selecionar um subconjunto das linhas em uma ordem em particular, podemos passar uma lista ou um ndarray de inteiros especificando a ordem desejada. Nesse exemplo, estamos retornando as linhas 2 e 4 de nosso array.

In [8]:
arr[[2, 4]]

array([[2., 2., 2.],
       [4., 4., 4.]])

É possível utilizar índices negativos, onde -1 é a última linha.

In [9]:
arr[[-1, -2]]

array([[4., 4., 4.],
       [3., 3., 3.]])

Vamos criar agora um novo array 5x3 contendo um sequencial de 0 a 14.

In [10]:
arr = np.arange(15).reshape(5, 3)

In [ ]:
arange: é uma versão da função range de Python com valor de array.
O array vai possuir 15 elementos com valores de 0 a 14.


In [11]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Ao passarmos vários índices de array, teremos como resultado um array unidimensional de elementos correspondentes a cada tupla de índices. Veja um exemplo.

In [12]:
arr[[0, 2, 4], [2, 1, 0]]

array([ 2,  7, 12])

Neste exemplo estamos retornando os elementos (0, 2), (2, 1) e (4, 0).

Agora veja como obter uma região retangular formada pela seleção de um subconjunto das linhas e colunas da matriz.

In [13]:
arr[[1, 2, 3]][:,[2,0,1]]

array([[ 5,  3,  4],
       [ 8,  6,  7],
       [11,  9, 10]])